//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAIL_SALON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceProduct
    {
        public int service_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Service tbl_Service { get; set; }
    }
}
